### ISSUE TITLE
Group chat using bridgefy

### ISSUE THREAD

**Issue by tejas-ardeshna** [bridgefy/bridgefy-ios-developer#1]
Hi first of all thanks for making this amazing library.

We have implemented one to one chat with this SDK which running smoothly. But now we need to add a feature like a group chat (not broadcast). So I was looking any method where the transmitter can send a message to multiple users instead of single one. For loop is an option but I want to transmit a message to all users without for loop like broadcast working.

Thanks.

**Comment by dannofx** [comment]
Hi, sorry for the excessively late response.

Unfortunately, Bridgefy doesn't count with a feature to send an encrypted direct message to a group or set of peers. The only options by now are to send a broadcast message or implement the loop you mentioned.
