### ISSUE TITLE
Sending Dictionary Keys

### ISSUE THREAD

**Issue by diegogarciar** [bridgefy/bridgefy-ios-developer#2]
My communication between my devices was working fine, I was able to communicate between an iPhone 5 (iOS 10) and an iPhone 6s (iOS 11.3). 
This week I discovered that I was receiving null dictionaries in my iPhone 6s for some dictionaries. After some testing I discovered that the I had a key called "type with value "offlineUpdate" which was causing the issue, the weird part is that iPhone 5 was receiving the dictionary correctly but iPhone 6s was not. I changed the value to "offline_update" and the dictionaries started receiving again. Maybe the issue is related to the new iOS 11.3 as it didn't happened before and its only happening in that device.

**Comment by dannofx** [comment]
Hi, Diego.

Sorry for the excessively late response, we have tried to replicate the problem with the values you provided, but we haven't been able to do it. Could you share your log using the [trace level](https://github.com/bridgefy/bridgefy-ios-developer#log-levels)?

Thanks.

**Comment by diegogarciar** [comment]
Hey, the problem occurred again and I fixed it by not sending message as encrypted. 
` _ = try? self.transmitter.send(data, toUser: user, options: [BFSendingOption.meshTransmission, /*BFSendingOption.encrypted*/])`

By the time I'm sending the packet, I'm certain that I have previously established a secure connection
From the center side the message was marked as sent but it was never received, I'll try to re-create the error this weekend with the trace level to share the log.

**Comment by dannofx** [comment]
Thank you. Sharing the dictionary you are trying to send (if possible) would also help.

**Comment by diegogarciar** [comment]
Sorry for the late response but I discovered that the issue wasn't related to dictionary keys. I got an iPhone XS and the communication issue kept happening with my iPhone 6s. I decided to reset the 6s and it seems it is now working fine. Good news my issue got fixed, bad news, I don't know what was causing it. Closing the issue
