### ISSUE TITLE
Venmo not showing in dropin ui. 

### ISSUE THREAD

**Issue by tejas-ardeshna** [bridgefy/bridgefy-ios-developer#3]
We are trying to integrate brain tree with venmo but somehow it's not showing in dropIn UI. We have enabled venmo in brain tree sandbox. please check attached image
![screen shot 2018-04-26 at 9 06 37 am](https://user-images.githubusercontent.com/12891361/39311123-b2380d6e-4989-11e8-8e77-087928a8729f.png)
![screen shot 2018-04-26 at 9 06 46 am](https://user-images.githubusercontent.com/12891361/39311124-b267664a-4989-11e8-8056-972179c6a781.png)

**Comment by dannofx** [comment]
This is not related to Bridgefy
