### ISSUE TITLE
Usage of UIWebView in the Bridgefy SDK?

### ISSUE THREAD

**Issue by zabojad** [bridgefy/bridgefy-ios-developer#5]
There is a major issue in the current version of the Bridgefy SDK for iOS. It seems to make use of the UIWebView, which is now forbidden for publishing apps on the App Store :

> ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

Three questions :

1 - What do you use this WebView for?

2 - Does the next version of the SDK address this issue?

3 - Is there a possibility of hotfixing the current SDK so that we do not have to wait for the next version?

**Comment by jorgeribs** [comment]
Hi! I'm Jorge, founder at Bridgefy. 

This issue has already been solved. Are you integrating with CocoPods or directly from the Framework? We recommend using CocoaPods, so you don't have to do manual updates. What version of the SDK are you working with?

**Comment by zabojad** [comment]
Hi @jorgeribs, 

We use a react native module with the following podspec:

```
s.source        = { :git => "https://bitbucket.org/bridgefy/react-native-bridgefy-sdk", :tag => "master" }
```

It seems not to fetch the latest version because:
```
$ pod outdated
Detected React Native module pods for BVLinearGradient, RNBridgefy, RNCAsyncStorage, RNGestureHandler, RNPermissions, RNSentry, RNVectorIcons, ReactNativeNavigation, RealmJS, react-native-camera, react-native-config, react-native-splash-screen, and toolbar-android
Updating spec repo `trunk`

Analyzing dependencies
The color indicates what happens when you run `pod update`
<green>	 - Will be updated to the newest version
<blue>	 - Will be updated, but not to the newest version because of specified version in Podfile
<red>	 - Will not be updated because of specified version in Podfile

The following pod updates are available:
- BFTransmitter 0.1.33 -> 0.1.33 (latest version 1.0.1)
```

**Comment by zabojad** [comment]
OK, I've forced the podspec to install latest BFTransmitter pod version and it now is 1.0.1 👍 
```
s.dependency 'BFTransmitter', '~> 1.0.1'
```
Thank you @jorgeribs !
